Added delete theme

diff --git a/.github/workflows/bigcommerce-shippy.yml b/.github/workflows/bigcommerce-shippy.yml
--- a/.github/workflows/bigcommerce-shippy.yml
+++ b/.github/workflows/bigcommerce-shippy.yml
@@ -136,4 +136,4 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Run shippy delete
-      run: echo "delete"
+      run: bash /shippy/exec/shippy.js bigcommerce feature --stop || echo "Failed trying to delete the Theme ... proceed anyway..."
